# =============================================================================
# backend/stubs/pyodbc.pyi
#
# Minimal type stub for pyodbc (https://github.com/mkleehammer/pyodbc).
#
# pyodbc is a compiled C extension — no Python source and no official stubs
# are available on PyPI. This stub covers the subset of the API used in this
# project (Connection, Cursor, connect(), Error) so that Pyright / Pylance can
# perform full type checking without falling back to "Unknown" types.
#
# The stub intentionally omits rarely used methods.  Extend it here if more
# pyodbc functionality is used in the future.
# =============================================================================

from __future__ import annotations

from collections.abc import Iterator
from typing import Any

# ---------------------------------------------------------------------------
# Exceptions (mirrors Python DB-API 2.0 exception hierarchy)
# ---------------------------------------------------------------------------

class Error(Exception): ...
class DatabaseError(Error): ...
class DataError(DatabaseError): ...
class OperationalError(DatabaseError): ...
class IntegrityError(DatabaseError): ...
class InternalError(DatabaseError): ...
class ProgrammingError(DatabaseError): ...
class NotSupportedError(DatabaseError): ...
class InterfaceError(Error): ...

# ---------------------------------------------------------------------------
# Row — a single result row (sequence + attribute access)
# ---------------------------------------------------------------------------

class Row:
    def __getattr__(self, name: str) -> Any: ...
    def __getitem__(self, index: int) -> Any: ...
    def __iter__(self) -> Iterator[Any]: ...
    def __len__(self) -> int: ...

# ---------------------------------------------------------------------------
# Cursor
# ---------------------------------------------------------------------------

class Cursor:
    rowcount: int
    description: list[tuple[str, Any, Any, Any, Any, Any, Any]] | None

    def execute(self, sql: str, /, *args: object) -> Cursor: ...
    def executemany(self, sql: str, seq_of_params: list[Any], /) -> Cursor: ...
    def fetchone(self) -> Row | None: ...
    def fetchall(self) -> list[Row]: ...
    def fetchmany(self, size: int = ...) -> list[Row]: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def close(self) -> None: ...
    def __iter__(self) -> Iterator[Row]: ...

# ---------------------------------------------------------------------------
# Connection
# ---------------------------------------------------------------------------

class Connection:
    autocommit: bool

    def cursor(self) -> Cursor: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def close(self) -> None: ...
    def execute(self, sql: str, /, *args: object) -> Cursor: ...

# ---------------------------------------------------------------------------
# Module-level API
# ---------------------------------------------------------------------------

def connect(
    connection_string: str,
    /,
    *,
    autocommit: bool = ...,
    timeout: int = ...,
    **kwargs: object,
) -> Connection: ...
