IF OBJECT_ID('dbo.CountryCodes2', 'U') IS NOT NULL
   AND OBJECT_ID('dbo.CountryCode2', 'U') IS NULL
BEGIN
    EXEC sp_rename 'dbo.CountryCodes2', 'CountryCode2';
END
GO

IF OBJECT_ID('dbo.PK_CountryCodes2', 'PK') IS NOT NULL
    EXEC sp_rename 'dbo.PK_CountryCodes2', 'PK_CountryCode2', 'OBJECT';
GO
IF OBJECT_ID('dbo.CK_CountryCodes2_format', 'C') IS NOT NULL
    EXEC sp_rename 'dbo.CK_CountryCodes2_format', 'CK_CountryCode2_format', 'OBJECT';
GO

IF OBJECT_ID('dbo.CountryCode2', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.CountryCode2 (
        country_code CHAR(2) NOT NULL,
        country_name NVARCHAR(200) NULL,
        CONSTRAINT PK_CountryCode2 PRIMARY KEY CLUSTERED (country_code),
        CONSTRAINT CK_CountryCode2_format CHECK (country_code LIKE '[A-Z][A-Z]')
    );
END
GO

IF COL_LENGTH('dbo.CountryCode2', 'country_name') IS NULL
    ALTER TABLE dbo.CountryCode2 ADD country_name NVARCHAR(200) NULL;
GO

MERGE dbo.CountryCode2 AS target
USING (VALUES
    ('AD', N'Andorra'),
    ('AE', N'United Arab Emirates'),
    ('AF', N'Afghanistan'),
    ('AG', N'Antigua and Barbuda'),
    ('AI', N'Anguilla'),
    ('AL', N'Albania'),
    ('AM', N'Armenia'),
    ('AO', N'Angola'),
    ('AQ', N'Antarctica'),
    ('AR', N'Argentina'),
    ('AS', N'American Samoa'),
    ('AT', N'Austria'),
    ('AU', N'Australia'),
    ('AW', N'Aruba'),
    ('AX', N'Åland Islands'),
    ('AZ', N'Azerbaijan'),
    ('BA', N'Bosnia and Herzegovina'),
    ('BB', N'Barbados'),
    ('BD', N'Bangladesh'),
    ('BE', N'Belgium'),
    ('BF', N'Burkina Faso'),
    ('BG', N'Bulgaria'),
    ('BH', N'Bahrain'),
    ('BI', N'Burundi'),
    ('BJ', N'Benin'),
    ('BL', N'Saint Barthélemy'),
    ('BM', N'Bermuda'),
    ('BN', N'Brunei Darussalam'),
    ('BO', N'Bolivia, Plurinational State of'),
    ('BQ', N'Bonaire, Sint Eustatius and Saba'),
    ('BR', N'Brazil'),
    ('BS', N'Bahamas'),
    ('BT', N'Bhutan'),
    ('BV', N'Bouvet Island'),
    ('BW', N'Botswana'),
    ('BY', N'Belarus'),
    ('BZ', N'Belize'),
    ('CA', N'Canada'),
    ('CC', N'Cocos (Keeling) Islands'),
    ('CD', N'Congo, Democratic Republic of the'),
    ('CF', N'Central African Republic'),
    ('CG', N'Congo'),
    ('CH', N'Switzerland'),
    ('CI', N'Côte d''Ivoire'),
    ('CK', N'Cook Islands'),
    ('CL', N'Chile'),
    ('CM', N'Cameroon'),
    ('CN', N'China'),
    ('CO', N'Colombia'),
    ('CR', N'Costa Rica'),
    ('CU', N'Cuba'),
    ('CV', N'Cabo Verde'),
    ('CW', N'Curaçao'),
    ('CX', N'Christmas Island'),
    ('CY', N'Cyprus'),
    ('CZ', N'Czechia'),
    ('DE', N'Germany'),
    ('DJ', N'Djibouti'),
    ('DK', N'Denmark'),
    ('DM', N'Dominica'),
    ('DO', N'Dominican Republic'),
    ('DZ', N'Algeria'),
    ('EC', N'Ecuador'),
    ('EE', N'Estonia'),
    ('EG', N'Egypt'),
    ('EH', N'Western Sahara'),
    ('ER', N'Eritrea'),
    ('ES', N'Spain'),
    ('ET', N'Ethiopia'),
    ('FI', N'Finland'),
    ('FJ', N'Fiji'),
    ('FK', N'Falkland Islands (Malvinas)'),
    ('FM', N'Micronesia, Federated States of'),
    ('FO', N'Faroe Islands'),
    ('FR', N'France'),
    ('GA', N'Gabon'),
    ('GB', N'United Kingdom of Great Britain and Northern Ireland'),
    ('GD', N'Grenada'),
    ('GE', N'Georgia'),
    ('GF', N'French Guiana'),
    ('GG', N'Guernsey'),
    ('GH', N'Ghana'),
    ('GI', N'Gibraltar'),
    ('GL', N'Greenland'),
    ('GM', N'Gambia'),
    ('GN', N'Guinea'),
    ('GP', N'Guadeloupe'),
    ('GQ', N'Equatorial Guinea'),
    ('GR', N'Greece'),
    ('GS', N'South Georgia and the South Sandwich Islands'),
    ('GT', N'Guatemala'),
    ('GU', N'Guam'),
    ('GW', N'Guinea-Bissau'),
    ('GY', N'Guyana'),
    ('HK', N'Hong Kong'),
    ('HM', N'Heard Island and McDonald Islands'),
    ('HN', N'Honduras'),
    ('HR', N'Croatia'),
    ('HT', N'Haiti'),
    ('HU', N'Hungary'),
    ('ID', N'Indonesia'),
    ('IE', N'Ireland'),
    ('IL', N'Israel'),
    ('IM', N'Isle of Man'),
    ('IN', N'India'),
    ('IO', N'British Indian Ocean Territory'),
    ('IQ', N'Iraq'),
    ('IR', N'Iran, Islamic Republic of'),
    ('IS', N'Iceland'),
    ('IT', N'Italy'),
    ('JE', N'Jersey'),
    ('JM', N'Jamaica'),
    ('JO', N'Jordan'),
    ('JP', N'Japan'),
    ('KE', N'Kenya'),
    ('KG', N'Kyrgyzstan'),
    ('KH', N'Cambodia'),
    ('KI', N'Kiribati'),
    ('KM', N'Comoros'),
    ('KN', N'Saint Kitts and Nevis'),
    ('KP', N'Korea, Democratic People''s Republic of'),
    ('KR', N'Korea, Republic of'),
    ('KW', N'Kuwait'),
    ('KY', N'Cayman Islands'),
    ('KZ', N'Kazakhstan'),
    ('LA', N'Lao People''s Democratic Republic'),
    ('LB', N'Lebanon'),
    ('LC', N'Saint Lucia'),
    ('LI', N'Liechtenstein'),
    ('LK', N'Sri Lanka'),
    ('LR', N'Liberia'),
    ('LS', N'Lesotho'),
    ('LT', N'Lithuania'),
    ('LU', N'Luxembourg'),
    ('LV', N'Latvia'),
    ('LY', N'Libya'),
    ('MA', N'Morocco'),
    ('MC', N'Monaco'),
    ('MD', N'Moldova, Republic of'),
    ('ME', N'Montenegro'),
    ('MF', N'Saint Martin (French part)'),
    ('MG', N'Madagascar'),
    ('MH', N'Marshall Islands'),
    ('MK', N'North Macedonia'),
    ('ML', N'Mali'),
    ('MM', N'Myanmar'),
    ('MN', N'Mongolia'),
    ('MO', N'Macao'),
    ('MP', N'Northern Mariana Islands'),
    ('MQ', N'Martinique'),
    ('MR', N'Mauritania'),
    ('MS', N'Montserrat'),
    ('MT', N'Malta'),
    ('MU', N'Mauritius'),
    ('MV', N'Maldives'),
    ('MW', N'Malawi'),
    ('MX', N'Mexico'),
    ('MY', N'Malaysia'),
    ('MZ', N'Mozambique'),
    ('NA', N'Namibia'),
    ('NC', N'New Caledonia'),
    ('NE', N'Niger'),
    ('NF', N'Norfolk Island'),
    ('NG', N'Nigeria'),
    ('NI', N'Nicaragua'),
    ('NL', N'Netherlands, Kingdom of the'),
    ('NO', N'Norway'),
    ('NP', N'Nepal'),
    ('NR', N'Nauru'),
    ('NU', N'Niue'),
    ('NZ', N'New Zealand'),
    ('OM', N'Oman'),
    ('PA', N'Panama'),
    ('PE', N'Peru'),
    ('PF', N'French Polynesia'),
    ('PG', N'Papua New Guinea'),
    ('PH', N'Philippines'),
    ('PK', N'Pakistan'),
    ('PL', N'Poland'),
    ('PM', N'Saint Pierre and Miquelon'),
    ('PN', N'Pitcairn'),
    ('PR', N'Puerto Rico'),
    ('PS', N'Palestine, State of'),
    ('PT', N'Portugal'),
    ('PW', N'Palau'),
    ('PY', N'Paraguay'),
    ('QA', N'Qatar'),
    ('RE', N'Réunion'),
    ('RO', N'Romania'),
    ('RS', N'Serbia'),
    ('RU', N'Russian Federation'),
    ('RW', N'Rwanda'),
    ('SA', N'Saudi Arabia'),
    ('SB', N'Solomon Islands'),
    ('SC', N'Seychelles'),
    ('SD', N'Sudan'),
    ('SE', N'Sweden'),
    ('SG', N'Singapore'),
    ('SH', N'Saint Helena, Ascension and Tristan da Cunha'),
    ('SI', N'Slovenia'),
    ('SJ', N'Svalbard and Jan Mayen'),
    ('SK', N'Slovakia'),
    ('SL', N'Sierra Leone'),
    ('SM', N'San Marino'),
    ('SN', N'Senegal'),
    ('SO', N'Somalia'),
    ('SR', N'Suriname'),
    ('SS', N'South Sudan'),
    ('ST', N'Sao Tome and Principe'),
    ('SV', N'El Salvador'),
    ('SX', N'Sint Maarten (Dutch part)'),
    ('SY', N'Syrian Arab Republic'),
    ('SZ', N'Eswatini'),
    ('TC', N'Turks and Caicos Islands'),
    ('TD', N'Chad'),
    ('TF', N'French Southern Territories'),
    ('TG', N'Togo'),
    ('TH', N'Thailand'),
    ('TJ', N'Tajikistan'),
    ('TK', N'Tokelau'),
    ('TL', N'Timor-Leste'),
    ('TM', N'Turkmenistan'),
    ('TN', N'Tunisia'),
    ('TO', N'Tonga'),
    ('TR', N'Türkiye'),
    ('TT', N'Trinidad and Tobago'),
    ('TV', N'Tuvalu'),
    ('TW', N'Taiwan, Province of China'),
    ('TZ', N'Tanzania, United Republic of'),
    ('UA', N'Ukraine'),
    ('UG', N'Uganda'),
    ('UM', N'United States Minor Outlying Islands'),
    ('US', N'United States of America'),
    ('UY', N'Uruguay'),
    ('UZ', N'Uzbekistan'),
    ('VA', N'Holy See'),
    ('VC', N'Saint Vincent and the Grenadines'),
    ('VE', N'Venezuela, Bolivarian Republic of'),
    ('VG', N'Virgin Islands (British)'),
    ('VI', N'Virgin Islands (U.S.)'),
    ('VN', N'Viet Nam'),
    ('VU', N'Vanuatu'),
    ('WF', N'Wallis and Futuna'),
    ('WS', N'Samoa'),
    ('YE', N'Yemen'),
    ('YT', N'Mayotte'),
    ('ZA', N'South Africa'),
    ('ZM', N'Zambia'),
    ('ZW', N'Zimbabwe')
) AS source(country_code, country_name)
ON target.country_code = source.country_code
WHEN MATCHED THEN
    UPDATE SET country_name = source.country_name
WHEN NOT MATCHED THEN
    INSERT (country_code, country_name)
    VALUES (source.country_code, source.country_name);
GO

ALTER TABLE dbo.CountryCode2 ALTER COLUMN country_name NVARCHAR(200) NOT NULL;
GO
